version: '3.8'

networks:
    ljps-net:
        driver: bridge

services:
    ################################################
    # MySQL: Relational Database Management System #
    ################################################
    db:
        build:
            context: ./db
        image: 212/database:1.0
        restart: unless-stopped
        networks:
            - ljps-net
        # environment:
        #     MYSQL_USER: is212
        #     MYSQL_PASSWORD: 123456
        #     MYSQL_ROOT_PASSWORD: root
        ports: 
            - "9906:3306"
    
    #########################################
    # phpMyAdmin: MySQL Database Management #
    #########################################
    phpmyadmin:
        image: phpmyadmin
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            - PMA_HOST=db
        ports:
            - "8080:80"
            
    
    ###############################
    # Skill: Skill service (CRUD) #
    ###############################
    skill:
        build: 
            context: ./
            dockerfile: ./skill/Dockerfile
        image: 212/skill:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5001:5001"
    ###############################
    # Role: Role service (CRUD) #
    ###############################            
    role:
        build:
            context: ./
            dockerfile: ./role/Dockerfile
        image: 212/role:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
            PYTHONUNBUFFERED: 1
        ports:
            - "5002:5002"
    
    ###############################
    # Course: Course service (CRUD) #
    ###############################
    courses:
        build: 
            context: ./
            dockerfile: ./course/Dockerfile
        image: 212/course:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5003:5003"

    ###############################
    # Learning Journey: Learning Journey service (CRUD) #
    ###############################
    learning_journey:
        build: 
            context: ./
            dockerfile: ./learning_journey/Dockerfile
        image: 212/learning_journey:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5004:5004"

    ###############################
    # Skills Courses: Skills Courses service (CRUD) #
    ###############################
    skills_courses:
        build: 
            context: ./
            dockerfile: ./skills_courses/Dockerfile
        image: 212/skills_courses:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5005:5005"

    ###############################
    # Skills Roles: Skills Roles service (CRUD) #
    ###############################
    skills_roles:
        build: 
            context: ./
            dockerfile: ./skills_roles/Dockerfile
        image: 212/skills_roles:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5006:5006"

    ###############################
    # Learning Journey Skills : Learning Journey Skills  service (CRUD) #
    ###############################
    lj_skills:
        build: 
            context: ./
            dockerfile: ./lj_skills/Dockerfile
        image: 212/lj_skills:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5007:5007"

    ###############################
    # Learning Journey Courses : Learning Journey Courses  service (CRUD) #
    ###############################
    lj_courses:
        build: 
            context: ./
            dockerfile: ./lj_courses/Dockerfile
        image: 212/lj_courses:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5008:5008"

    ###############################
    # Learning Journey Roles : Learning Journey Roles service (CRUD) #
    ###############################
    lj_roles:
        build: 
            context: ./
            dockerfile: ./lj_roles/Dockerfile
        image: 212/lj_roles:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5009:5009"

    ###############################
    # groups : groups service (CRUD) #
    ###############################
    groups:
        build: 
            context: ./
            dockerfile: ./groups/Dockerfile
        image: 212/groups:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5010:5010"

    ###############################
    # staff : staff service (CRUD) #
    ###############################
    staff:
        build: 
            context: ./
            dockerfile: ./staff/Dockerfile
        image: 212/staff:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5011:5011"

    ###############################
    # registration : registration service (CRUD) #
    ###############################
    registration:
        build: 
            context: ./
            dockerfile: ./registration/Dockerfile
        image: 212/registration:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5012:5012"