version: '3.8'

networks:
    ljps-net:
        driver: bridge

services:
    ################################################
    # MySQL: Relational Database Management System #
    ################################################
    db:
        build:
            context: ./db
        image: 212/database:1.0
        restart: unless-stopped
        networks:
            - ljps-net
        # environment:
        #     MYSQL_USER: is212
        #     MYSQL_PASSWORD: 123456
        #     MYSQL_ROOT_PASSWORD: root
        ports: 
            - "9906:3306"
    
    #########################################
    # phpMyAdmin: MySQL Database Management #
    #########################################
    phpmyadmin:
        image: phpmyadmin
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            - PMA_HOST=db
        ports:
            - "8080:80"
            
    ###############################
    # Role: Role service (CRUD) #
    ###############################            
    role:
        build:
            context: ./
            dockerfile: role/Dockerfile
        image: 212/role:1.0
        restart: always
        environment:
            dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/ljps
            PYTHONUNBUFFERED: 1
        ports:
            - "5002:5002"
    
    ###############################
    # Skill: Skill service (CRUD) #
    ###############################
    skill:
        build: 
            context: ./
            dockerfile: ./skill/Dockerfile
        image: 212/skill:1.0
        restart: always
        networks:
            - ljps-net
        depends_on:
            - db
        environment:
            dbURL: mysql+mysqlconnector://root:root@db:3306/ljps
        ports:
            - "5001:5001"
